flowchart TD

A[Triple Gift Mechanics]

B[Efficient Friendship Farming Strategy]

subgraph Guides
D[RF5 Daily Friendship Farming Guide]
E[RF4SP Daily Friendship Farming Guide]
end

C[The Hidden Cost of Shipping Everything]

A --> B

B --> C
B --> D
B --> E
